#!/usr/bin/env python3
"""Family-level (cluster) bootstrap of the headline margins. The 245 twin pairs are generated by only
18 independent mathematical cores, so papers/queries are not independent; the honest replication unit
is the FAMILY. This resamples the 18 cores with replacement (B=2000), rebuilds the cross-field pairs
within the resampled set, and recomputes the abstract/skeleton/fingerprint AP and their paired margins.
TF-IDF only (no embedders, no network). Run from the package root:  python src/family_bootstrap.py"""
import sys
import numpy as np
sys.path.insert(0, ".")
sys.path.insert(0, "src")
import embed as E      # noqa: E402
import reproduce as R  # noqa: E402
from sklearn.metrics import average_precision_score  # noqa: E402

DATA = "data"
lab, mfield = R.load_labels(), R.load_field()
absr = E.load_rep(DATA, "abstract")
ids, fld, fam = R.corpus("curated", absr, lab, mfield)
N = len(ids)
field = np.array([fld[i] for i in ids])
family = np.array([fam[i] for i in ids], dtype=object)


def sim(texts):
    return E.cosine_matrix(R.vectors(texts, "tfidf"))


S = {
    "abstract":    sim([absr[i] for i in ids]),
    "skeleton":    sim([R.faceted_text("skeletons_faceted_haiku", i, mech_only=True) for i in ids]),
    "fingerprint": sim([R.faceted_text("skeletons_faceted_haiku", i) for i in ids]),
}

iu, ju = np.triu_indices(N, 1)
cr0 = field[iu] != field[ju]
pos0 = ((family[iu] != "") & (family[iu] == family[ju]))[cr0].astype(int)
pt = {m: average_precision_score(pos0, S[m][iu[cr0], ju[cr0]]) for m in S}
print(f"point AP: abstract {pt['abstract']:.3f}, skeleton {pt['skeleton']:.3f}, fingerprint {pt['fingerprint']:.3f}")

fams = sorted(set(family[family != ""]))
members = {f: np.where(family == f)[0] for f in fams}
print(f"{len(fams)} families resampled with replacement, B=2000")
np.random.seed(0)
B = 2000
bd = {"fp_abs": [], "sk_abs": [], "fp_sk": []}
for _ in range(B):
    rf = np.random.choice(len(fams), len(fams), replace=True)
    idx = np.concatenate([members[fams[k]] for k in rf])
    ii, jj = np.triu_indices(len(idx), 1)
    gi, gj = idx[ii], idx[jj]
    cr = field[gi] != field[gj]
    gi, gj = gi[cr], gj[cr]
    p = ((family[gi] != "") & (family[gi] == family[gj])).astype(int)
    if p.sum() == 0:
        continue
    a = average_precision_score(p, S["abstract"][gi, gj])
    s = average_precision_score(p, S["skeleton"][gi, gj])
    f = average_precision_score(p, S["fingerprint"][gi, gj])
    bd["fp_abs"].append(f - a)
    bd["sk_abs"].append(s - a)
    bd["fp_sk"].append(f - s)


def rep(name, key, point):
    d = np.array(bd[key])
    lo, hi = np.percentile(d, 2.5), np.percentile(d, 97.5)
    pval = 2 * min((d <= 0).mean(), (d >= 0).mean())
    print(f"  {name:26} +{point:.3f}  [{lo:+.3f}, {hi:+.3f}]  p={pval:.4f}")


print("family-level cluster bootstrap margins:")
rep("skeleton vs abstract", "sk_abs", pt["skeleton"] - pt["abstract"])
rep("fingerprint vs abstract", "fp_abs", pt["fingerprint"] - pt["abstract"])
rep("fingerprint vs skeleton", "fp_sk", pt["fingerprint"] - pt["skeleton"])
